import './styles/reset.css';
import './styles/global.css';
import { Quicksand } from 'next/font/google';
import React from 'react';
import { Providers } from './providers';

const quicksand = Quicksand({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin-ext'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={quicksand.className}>
      <body>
        {/*<main className="container">*/}
          <Providers>{children}</Providers>
        {/*</main>*/}
      </body>
    </html>
  );
}
